_BASE_: "../../../../configs/Base-RCNN-DilatedC5.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  PIXEL_MEAN: [73, 83, 72]
  PIXEL_STD: [47.67, 48.49, 47.74]
  BACKBONE:
    FREEZE_AT: 0
  SEM_SEG_HEAD:
    NAME: "DeepLabV3Head"
    IN_FEATURES: ["res5"]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    CONVS_DIM: 256
    COMMON_STRIDE: 16
    NUM_CLASSES: 19
    # LOSS_TYPE: "hard_pixel_mining"
    LOSS_TYPE: "cross_entropy"
DATASETS:
  TRAIN: ("bdd100k_sem_seg_train",)
  TEST: ("bdd100k_sem_seg_val",)
SOLVER:
  BASE_LR: 0.02
  MAX_ITER: 60000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 16
INPUT:
  MIN_SIZE_TRAIN: (512, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  # MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  # MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 4096
  MIN_SIZE_TEST: 1024 
  MAX_SIZE_TEST: 2048 
  TEST_SIZE: (1024, 2048)
  CROP:
    ENABLED: True
    FIXED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
  FLIP:
    ENABLED: False
DATALOADER:
  NUM_WORKERS: 10
