_BASE_: Base-DeepLabV3-myencoder-Semantic.yaml
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # PIXEL_MEAN: [0.0, 0.0, 0.0]
  # PIXEL_STD: [1.0, 1.0, 1.0]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    OUT_FEATURES: ["res2", "res5"]
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "basic"
    # STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NAME: "DeepLabV3PlusHead"
    IN_FEATURES: ["res2", "res5"]
    PROJECT_FEATURES: ["res2"]
    PROJECT_CHANNELS: [48]
    NORM: "SyncBN"
    COMMON_STRIDE: 4
SOLVER:
  MAX_ITER: 60000
INPUT:
  FORMAT: "RGB"
