_BASE_: Base-DeepLabV3-myencoder-Semantic.yaml
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # PIXEL_MEAN: [123.675, 116.280, 103.530]
  # PIXEL_STD: [58.395, 57.120, 57.375]
  # PIXEL_MEAN: [73.0, 83.0, 72.0]
  # PIXEL_STD: [47.67, 48.49, 47.74]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "basic"
    # STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NAME: "DeepLabV3Head"
    NORM: "SyncBN"
SOLVER:
  MAX_ITER: 40000
INPUT:
  FORMAT: "RGB"
