_BASE_: Base-DeepLabV3-OS16-Semantic.yaml
MODEL:
  WEIGHTS: "detectron2://DeepLab/R-103.pkl"
  # PIXEL_MEAN: [0.0, 0.0, 0.0]
  # PIXEL_STD: [1.0, 1.0, 1.0]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 101
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NAME: "DeepLabV3Head"
    NORM: "SyncBN"
SOLVER:
  MAX_ITER: 90000
INPUT:
  FORMAT: "RGB"
